#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#
# This shiny app is built from scripts generated by Marc Seal & Richard Beare & Stack Overflow
# see the simulated data script here: https://github.com/mdc-2017/structural-workshop/blob/master/Simulated_Data/MDC_Workshop_Simulated_Data_FINAL.Rmd
#
#


library(shiny)
packages <- c("lme4", "nlme", 
              "ggplot2", "dplyr", 
              "tidyr", "data.table",
              "longpower", "simr", "powerlmm",
              "MBESS","sjPlot","GGally","knitr",
              "tidyverse","simstudy","arm")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))
}
lapply(packages, library, character.only = TRUE)

simdatalong<-function(N,DIST,DELTA){
  def_T1 <- defData(varname = "Age.1", dist="uniform", formula = "6;9",id = "ID")             # create random uniform distribution of age range 6-9 
  def_T1 <- defData(def_T1,varname = "spread", dist = "normal", formula = "1",variance=0.01)  # create random "spread" factor for adjusting values 
  def_T1 <- defData(def_T1, varname = "nCount", dist = "uniform", formula = paste0(DIST))        # define nCount = number of measurements for an individual   
  def_T1 <- defData(def_T1, varname = "mInterval", dist = "uniform", formula = "0.8;1.2")     # define mInterval = the average time (years) between intervals for a subject
  def_T1 <- defData(def_T1, varname = "vInterval", dist = "nonrandom", formula = 0.07)        # define vInterval = specifies the variance of those interval times
  
  # Generate Simulated Data    
  SIM_DATA <- genData(N, def_T1)
  
  SIM_DATA$nCount <- round(SIM_DATA$nCount)
  
  ## Create Longitudinal dataframe based on parameters defined above      
  SIM_DATA_long <- addPeriods(SIM_DATA, id="ID")
  
  # Brain Measure decreasing at X% per year with added noise
  def_Long  <- defDataAdd(varname = "brain.measure",
                          dist = "normal",
                          formula = paste0("2.8*(spread*(1",DELTA,"*time))"),
                          variance = 0.018)
  
  
  
  # Add Age dependent variables to longitudinal dataframe     
  SIM_DATA_long  <- addColumns(def_Long,SIM_DATA_long)
  
  # create a new column with Age term
  SIM_DATA_long <- mutate(SIM_DATA_long, Age = Age.1 + time) 
  
}

mixed.power<-function(N, DIST, DELTA, n.sims){
  signif<-rep(NA, n.sims) #note that you can specify number of simulations - default is 1000
  for(s in 1:n.sims){
    fake.data<-simdatalong(N, DIST, DELTA)                                               #calls in data simulation function
    lme.power.null<-lmer(brain.measure~1+(1|ID), REML = FALSE,data=fake.data)
    lme.power<-lmer(brain.measure~Age+(1|ID), REML = FALSE,data=fake.data)            #estimates mixed effect model using each simulated dataset
    theta.hat<-fixef(lme.power)["Age"]                                  #saves age coefficients from each simulated dataset 
    theta.se<-se.fixef(lme.power)["Age"]                                #saves standard error of age coefficients from each simulated dataset
    signif[s]<-ifelse(anova(lme.power.null,lme.power)$`Pr(>Chisq)`[2]<.05, 1, 0)#assigns value of 1 to significant coefficients 0 to ns coefficients
  }
  power<-mean(signif, na.rm=T) #calculates proportion of significant models out of # of simulated datasets... 
  return(power)
}


# Define UI for application that draws a histogram
ui <- fluidPage(
   
   # Application title
   titlePanel("Longitudinal Developmental MRI Power Calculator"),
   
   # Sidebar with a slider input for number of bins 
   sidebarLayout(
      sidebarPanel(
         sliderInput("N",
                     "Number of participants:",
                     min = 1,
                     max = 500,
                     value=250),
         # Input: Decimal interval with step value ----
         sliderInput("low", "Minimum Number of Scans:",
                     min = 1, max = 7,
                     value = 1, step = 1),
         
         # Input: Specification of range within an interval ----
         sliderInput("high", "Maximum Number of Scans:",
                     min = 2, max = 8,
                     value = 2, step = 1),
      # Input: Decimal interval with step value ----
      sliderInput("DELTA", "Percent Change in Brain Volume:",
                  min = -5, max = 0,
                  value = 0.0, step = .25)
      ),
      # Show a plot of the generated distribution
      mainPanel(
        textOutput("selected_var")
      )
   )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
  
  output$selected_var <- renderText({
     
     mixed.power(N=input$N,
                 DIST=paste0(input$low,";",input$high),
                 DELTA=(input$DELTA)*.01,
                 n.sims=100)
   })
}

# Run the application 
shinyApp(ui = ui, server = server)
