#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#
# This shiny app is built from scripts generated by Marc Seal & Richard Beare & Stack Overflow
# see the simulated data script here: https://github.com/mdc-2017/structural-workshop/blob/master/Simulated_Data/MDC_Workshop_Simulated_Data_FINAL.Rmd
#
#




packages <- c("lme4", "nlme", 
              "ggplot2", "dplyr", 
              "tidyr", "data.table",
              "longpower", "simr", "powerlmm",
              "MBESS","sjPlot","GGally","knitr",
              "tidyverse","simstudy","arm","shinythemes","shinyjs")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))
}
lapply(packages, library, character.only = TRUE)

########### Marc

# Set up using Keith Goldfield's "Longitudinal data with varying observation and interval times"
#  https://cran.r-project.org/web/packages/simstudy/vignettes/simstudy.html



simdatalong<-function(N,DIST,DELTA,CUSTOM,INTERCEPT,VARIANCE){
  def_T1 <- defData(varname = "Age.1", dist="uniform", formula = "6;9",id = "ID")             # create random uniform distribution of age range 6-9 
  def_T1 <- defData(def_T1,varname = "spread", dist = "normal", formula = "1",variance=0.01)  # create random "spread" factor for adjusting values 
  def_T1 <- defData(def_T1, varname = "mInterval", dist = "uniform", formula = "0.8;1.2")     # define mInterval = the average time (years) between intervals for a subject
  def_T1 <- defData(def_T1, varname = "vInterval", dist = "nonrandom", formula = 0.07)        # define vInterval = specifies the variance of those interval times
  
  # Generate Simulated Data    
  SIM_DATA <- genData(N, def_T1)
  
  SIM_DATA$nCount <- sample(1:DIST, size = N, replace = TRUE, prob = 1:DIST)
  
  ## Create Longitudinal dataframe based on parameters defined above      
  SIM_DATA_long <- addPeriods(SIM_DATA, id="ID")
  
  
  # Brain Measure decreasing at DELTA% per year with added noise
  if (CUSTOM == "No") {
    def_Long  <- defDataAdd(varname = "brain.measure",
                            dist = "normal",
                            formula = paste0("2.8*(spread*(1",DELTA,"*time))"),
                            variance = 0.018)
  } else {
    def_Long  <- defDataAdd(varname = "brain.measure",
                            dist = "normal",
                            formula = paste0(INTERCEPT,"*(spread*(1",DELTA,"*time))"),
                            variance = VARIANCE)
  }
  
  # Add Age dependent variables to longitudinal dataframe     
  SIM_DATA_long  <- addColumns(def_Long,SIM_DATA_long)
  
  
  # create a new column with Age term
  SIM_DATA_long <- mutate(SIM_DATA_long, Age = Age.1 + time) 
  
  SIM_DATA_long$ID <- as.factor(SIM_DATA_long$ID)
  
  SIM_DATA_long$time <- as.factor(SIM_DATA_long$time)
  # Return
  SIM_DATA_long
}


#number of participants (J) with a given number of brains per participant (K)

mixed.power<-function(N,DIST,DELTA,CUSTOM,INTERCEPT,VARIANCE, n.sims){
  signif<-rep(NA, n.sims) #note that you can specify number of simulations - default is 1000
  for(s in 1:n.sims){
    if (CUSTOM=="Yes"){
      fake.data<-simdatalong(N,DIST,DELTA,CUSTOM,INTERCEPT,VARIANCE)                  #calls in data simulation function
    } else {
      fake.data<-simdatalong(N,DIST,DELTA,CUSTOM,INTERCEPT,VARIANCE)           #calls in data simulation function
    }
    lme.power.null<-lmer(brain.measure~1+(1|ID), REML = FALSE,data=fake.data)
    lme.power<-lmer(brain.measure~Age+(1|ID), REML = FALSE,data=fake.data)            #estimates mixed effect model using each simulated dataset
    theta.hat<-fixef(lme.power)["Age"]                                  #saves age coefficients from each simulated dataset 
    theta.se<-se.fixef(lme.power)["Age"]                                #saves standard error of age coefficients from each simulated dataset
    signif[s]<-ifelse(anova(lme.power.null,lme.power)$`Pr(>Chisq)`[2]<.05, 1, 0)#assigns value of 1 to significant coefficients 0 to ns coefficients
  }
  power<-mean(signif, na.rm=T) #calculates proportion of significant models out of # of simulated datasets... 
  return(power)
}



# Define UI for application that draws a histogram
ui <- fluidPage(theme = shinytheme("superhero"),
                useShinyjs(),
                inlineCSS(list('#text3 ' = 'text-align: center')),
                tags$head(tags$style("
                  #container * {  
   display: inline;
                     }"),
                          HTML("
        <script>
                               $(document).ready(function(){
                               $(\".js-range-slider\").ionRangeSlider({
                               hide_min_max: false,
                               hide_from_to: true
                               });
                               });
                               </script>
                               ")
                          ),
                tags$style(type = "text/css", "
        .irs-min {visibility:visible !important;}
                           .irs-max {color:white}
                           .irs-min {color:white}
                           "),
                
   # Application title
   titlePanel("Longitudinal MRI Power Calculator"),
   
   # Sidebar with a slider input for number of bins 
   sidebarLayout(
      sidebarPanel(
         sliderInput("N",
                     "Number of participants: ",
                     min = 1,
                     max = 500,
                     value=250),
         
       
         # Input: Decimal interval with step value ----
       
          numericInput("DIST", "Number of Scans: ",
                      2,min=2,width='100%'),
        
         
      # Input: Decimal interval with step value ----
      sliderInput("DELTA", "Percent Change in Brain Volume: ",
                  min = -5, max = 0,
                  value = -1.0, step = .25),
      
      selectInput("CUSTOM", "Would you like to set custom parameters for the Intercept and Variance?",
                  c("No",
                       "Yes")),
      
      conditionalPanel(
        condition = "input.CUSTOM == 'Yes'",
        numericInput("INTERCEPT", "Intercept Value: ", 0),
        numericInput("VARIANCE", "Variance Value: ", 0)
         )
          ),
  
      # Show a plot of the generated distribution
      mainPanel(
        div(id="container",h5('With this study design, your predicted power woule be: ', textOutput("selected_var")))
      )
   )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
  output$text1 <- renderText({paste("You have selected")})
  output$selected_var <- renderText({

    mixed.power(N=input$N,
                DIST=input$DIST,
                DELTA=(input$DELTA)*.01,
                CUSTOM=input$CUSTOM,
                INTERCEPT= input$INTERCEPT,
                VARIANCE= input$VARIANCE,
                n.sims=100)
   })
}

# Run the application 
shinyApp(ui = ui, server = server)
