#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#
# This shiny app is built from scripts generated by Marc Seal & Richard Beare & Stack Overflow
# see the simulated data script here: https://github.com/mdc-2017/structural-workshop/blob/master/Simulated_Data/MDC_Workshop_Simulated_Data_FINAL.Rmd
#
#

library("lme4")
library("GGally")
library("knitr")
library("tidyverse")
library("simstudy")
library("arm")
library("shinythemes")
library("shinyjs")
library("stringr")


text_settings <-
  theme(text = element_text(size = 15)) +
  theme(plot.title = element_text(size =25,face='bold')) +
  theme(axis.title.x = element_text(face='bold',size=20)) +
  theme(axis.title.y = element_text(face='bold',size=20)) +
  theme(axis.text.x = element_text(size = 15)) +
  theme(axis.text.y = element_text(size = 15)) +
  theme(axis.ticks = element_blank())
apatheme=theme_bw()+
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.border=element_blank(),
        axis.line=element_line(),
        text=element_text(family='Helvetica'),
        plot.title = element_text(hjust = 0.5))
########### Marc

# Set up using Keith Goldfield's "Longitudinal data with varying observation and interval times"
#  https://cran.r-project.org/web/packages/simstudy/vignettes/simstudy.html

simdatalong<-function(N,DIST,DELTA,CUSTOM,INTERCEPT,VARIANCE){
  #1 create random uniform distribution of age range 6-9 
  #2 create random "spread" factor for adjusting values 
  #3 define mInterval = the average time (years) between intervals for a subject
  #4 define vInterval = specifies the variance of those interval times
  def_T1 <- data.table::rbindlist(
    list(simstudy::defData(varname = "Age.1", dist="uniform", formula = "6;9"),
         simstudy::defData(varname = "spread", dist = "normal", formula = "1",variance=0.01),
         simstudy::defData(varname = "mInterval", dist = "uniform", formula = "0.8;1.2"),
         simstudy::defData(varname = "vInterval", dist = "nonrandom", formula = 0.07)))
  # Generate Simulated Data    
  SIM_DATA <- simstudy::genData(N, def_T1)
  SIM_DATA[, nCount := sample(1:DIST, size = N, replace = TRUE, prob = 1:DIST)]
  SIM_DATA[, ID := 1:.N]
  
  ## Create Longitudinal dataframe based on parameters defined above      
  SIM_DATA_long <- addPeriods(SIM_DATA, id="ID")
 
  # Brain Measure decreasing at DELTA% per year with added noise
  if (CUSTOM == "No") {
    def_Long  <- defDataAdd(varname = "brain.measure",
                            dist = "normal",
                            formula = paste0("2.8*(spread*(1",DELTA,"*time))"),
                            variance = 0.018)
  } else {
    def_Long  <- defDataAdd(varname = "brain.measure",
                            dist = "normal",
                            formula = paste0(INTERCEPT,"*(spread*(1",DELTA,"*time))"),
                            variance = VARIANCE)
  }
  
  # Add Age dependent variables to longitudinal dataframe     
  SIM_DATA_long  <- addColumns(def_Long,SIM_DATA_long)
  
  # create a new column with Age term
  SIM_DATA_long[, Age := Age.1 + time]
  # Return
  return(SIM_DATA_long)
}

#number of participants (J) with a given number of brains per participant (K)

# Define UI for application that draws a histogram
ui <- fluidPage(theme = shinytheme("superhero"),
                useShinyjs(),
                inlineCSS(list('#text3 ' = 'text-align: center')),
                tags$head(tags$style("
                                     #container * {  
                                     display: inline;
                                     }"),
                          HTML("
                               <script>
                               $(document).ready(function(){
                               $(\".js-range-slider\").ionRangeSlider({
                               hide_min_max: false,
                               hide_from_to: true
                               });
                               });
                               </script>
                               ")
                ),
                tags$style(type = "text/css", "
                           .irs-min {visibility:visible !important;}
                           .irs-max {color:white}
                           .irs-min {color:white}
                           "),
                
                # Application title
                titlePanel("Longitudinal MRI Power Calculator"),
                
                # Sidebar with a slider input for number of bins 
                sidebarLayout(
                  sidebarPanel(
                    sliderInput("N",
                                "Number of Participants: ",
                                min = 0,
                                max = 500,
                                value=250),
                    
                    
                    # Input: Number of Scans per participant
                    
                    numericInput("DIST", "Max number of Scans per Participant: ",
                                 2,min=2,width='100%'),
                    
                    
                    # Input: Percent change in brain volume 
                    sliderInput("DELTA", "Percent Change in Brain Volume: ",
                                min = -5, max = 0,
                                value = -1.0, step = .25),
                    
                    # Input: Number of simulations
                    numericInput("n.sims", "Number of Simulations: ",
                                 100,min=1,width='100%'),
                    
                    # Input: Lets user select if they would like a graph
                    selectInput("graph", "Would you like create a graph? Warning: Depending on your parameters (e.g., high N, high simulation), this option could take a while.",
                                c("No",
                                  "Yes")),
                    # Input: If they did want to create a graph, input min sample size 
                    conditionalPanel(
                      condition = "input.graph == 'Yes'",
                      numericInput("min.sample.size", "Minimum sample size: ", 10)
                    ),
                    # Input: If they did want to create a graph, input step size 
                    conditionalPanel(
                      condition = "input.graph == 'Yes'",
                      numericInput("sample.step.size", "For each simulation, increase sample by: ", 20)
                    ),
                    # Input: Lets user select if they would like to customize parameters
                    selectInput("CUSTOM", "Would you like to set custom parameters for the Intercept and Variance?",
                                c("No",
                                  "Yes")),
                    
                    # Input: If they did want to add custom parameters, now's their chance! 
                    conditionalPanel(
                      condition = "input.CUSTOM == 'Yes'",
                      numericInput("INTERCEPT", "Intercept Value: ", NA),
                      numericInput("VARIANCE", "Variance Value: ", NA)
                    ),
                      
                    actionButton("calculate", "Calculate",width='100%')
                    ),
                  
                 
                  
                  # Show a plot of the generated distribution
                  mainPanel(
                    div(id="container",h5(textOutput("sample_size"))),
                    div(id="container",h5(textOutput("selected_var"))),
                    plotOutput("plot1")

                  )
                )
              )

# Define server logic required to draw a histogram
server <- function(input, output) {
  mixed.power<-function(N,DIST,DELTA,CUSTOM,INTERCEPT,VARIANCE, n.sims, PRINTCI = F){
    #faster to get all data for simulation at once
    fake.data<-simdatalong(N*n.sims,DIST,DELTA,CUSTOM,INTERCEPT,VARIANCE)           #calls in data simulation function
    #faster to use data.table features
    fake.data[, simgrp := (ID-1) %/% N + 1]
    
    sigdif <- function(brain.measure, Age, ID, simgrp, measure = 'chisq', IC_cut = 6, alpha = .05){
      lme.power.null<-lmer(brain.measure~1+(1|ID), REML = FALSE)
      lme.power<-lmer(brain.measure~Age+(1|ID), REML = FALSE)
      if((simgrp/n.sims*100) %% 10 == 0) incProgress(1/n.sims*(n.sims/10), detail = paste("Simulation", simgrp))
      if(measure == 'AIC'){
        return(diff(AIC(lme.power.null, lme.power)$AIC) < IC_cut)
      } else if(measure == 'BIC'){
        return(diff(BIC(lme.power.null, lme.power)$BIC) < IC_cut)
      } else if(measure == 'chisq'){
        return(anova(lme.power.null,lme.power)$`Pr(>Chisq)`[2] < alpha)
      }
      
    }

    withProgress(message = 'Running Simulations', value = 0, {
      fake.data[, sigdif := sigdif(brain.measure, Age, ID, simgrp), by = simgrp]
    })
    power<-mean(fake.data$sigdif, na.rm=T)
    se_power <- (power*(1-power)/n.sims)^.5
    ci_power <- round(c(power + c(-1,1)*qnorm(.975)*se_power),2)
    if(PRINTCI){
      return(paste0(round(power,2), ' [', ci_power[1], ', ', ci_power[2], ']'))
    } else {
      return(list(power = power, lower = ci_power[1], upper = ci_power[2]))
    }
  }
  graph.power<-function(N,DIST,DELTA,CUSTOM,INTERCEPT,VARIANCE,n.sims,min.N=10,step.N=20){
    KK<-seq(min.N, N, by=step.N)       #will ieterate from min.N cases to the max.K specified in the function above
    Y<-rep(NA, length(KK))        #Empty vector to contain power estimates from mixed.power () function
    upper<-rep(NA, length(KK))
    lower<-rep(NA, length(KK))
    NN<-rep(DIST, length(KK))        #Repeates the number of habitats you specified to equal the length of the KK vector 
    withProgress(message = 'Creating Graph', value = 0, {
    for(i in 1:length(KK)){
      powerest <- mixed.power(KK[i], NN[i],DELTA,CUSTOM,INTERCEPT,VARIANCE,n.sims)
      Y[i] <- powerest$power #runs mixed power function and stores results one at a time
      upper[i] <- ifelse(powerest$upper > 1, 1, powerest$upper)
      lower[i] <- ifelse(powerest$lower < 0, 0, powerest$lower)
      incProgress(1/length(KK), detail = paste(str_replace_all(string=paste(round(i/length(KK)*100,0),"%"), pattern=" ",replacement = "")," complete"))
    }
    })
    DF<-as.data.frame(cbind(KK, Y, lower, upper)) #creates data frame for plotting
    colnames(DF)<-c("KK", "Y", "lower", "upper")
    #Code below provides a basic power plot with a horizontal line at .80 
    g1<-ggplot(aes(x=KK, y=Y), data=DF) +
      geom_errorbar(aes(ymin = lower, ymax = upper), color = '#555555', width = 0) +
      geom_smooth(se=F,color="#d75452")+
      geom_hline(yintercept = .8, lty="dashed", col="#5b6976", lwd=1) +
      xlab("\nSample Size")+ylab("\nPower")+ 
      ggtitle("Power Analysis") +
      scale_y_continuous(limits = c(0, 1)) +
      apatheme +
      text_settings +
      theme(axis.title=element_text(color = "#ebebeb"),axis.title.y=element_text(margin = unit(c(0, 7, 0, 0), "mm")),axis.text=element_text(color="#ebebeb"),axis.line=element_line(color="#ebebeb"),axis.ticks=element_line(color="#ebebeb"),plot.title=element_text(color="#ebebeb"),plot.background = element_rect(fill = "#2c3e4f",colour="#2c3e4f"),panel.background = element_rect(fill="#2c3e4f",color="#2c3e4f"))
    return(g1)
  }
  
  output$sample_size = eventReactive(input$N, {
    show("sample_size")
    paste("You selected a sample size of " ,input$N)
  })
  
observeEvent(input$calculate,{
  
  
  if (input$graph=="No") {
      observeEvent(isolate(input$calculate),{
      hide("plot1")
      show("selected_var")
      output$selected_var <- renderText({
        paste0("With ",input$N," participants with this study design, your predicted power would be (with 95% CI): ", 
          isolate({mixed.power(N=input$N,
                          DIST=input$DIST,
                          DELTA=(input$DELTA)*.01,
                          CUSTOM=input$CUSTOM,
                          INTERCEPT= input$INTERCEPT,
                          VARIANCE= input$VARIANCE,
                          n.sims=input$n.sims, PRINTCI = T)}))
        })
      })
    }
  else {observeEvent(isolate(input$calculate),{
    show("plot1")
    hide("selected_var")
    output$plot1 <- renderPlot({
      isolate(graph.power(N=input$N,
                          DIST=input$DIST,
                          DELTA=(input$DELTA)*.01,
                          CUSTOM=input$CUSTOM,
                          INTERCEPT= input$INTERCEPT,
                          VARIANCE= input$VARIANCE,
                          n.sims=input$n.sims,
                          min.N=input$min.sample.size,
                          step.N=input$sample.step.size))
        },height = 400, width = 600)
      })
    }
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
